Controllers/CasaDeShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using casaDeShows.Repositorios;
using casaDeShows.Models; 
using Microsoft.AspNetCore.Authorization;
namespace casaDeShows.Controllers
{
    public class CasaDeShowController:Controller
    {   
        private readonly CasaDeShowRepositorio _casaDeShowRepositorio;
        public CasaDeShowController (CasaDeShowRepositorio casaDeShowRepositorio){
            _casaDeShowRepositorio = casaDeShowRepositorio;
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult ListarCasasDeShow(){
            var listaDeCasas = _casaDeShowRepositorio.MostrarCasasDeShow();
            return View(listaDeCasas);
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult NovaCasaDeShowFormulario(){
            return View();
        }
        [HttpPost]
        public ActionResult NovaCasaDeShow(CasaDeShow casa){
            if(ModelState.IsValid){
                _casaDeShowRepositorio.AdicionarCasaDeShow(casa);
                return RedirectToAction("Index","Home");
            }
            else{
                return View("NovaCasaDeShowFormulario");
            }
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult EditarCasaDeShow(int id){
            var editaCasaDeShow = _casaDeShowRepositorio.BuscarCasaDeShow(id);
            return View(editaCasaDeShow);
        }
        [HttpPost]
        public IActionResult EditarCasaDeShow(CasaDeShow casa){
            if(ModelState.IsValid){
                _casaDeShowRepositorio.EditarCasaDeShow(casa);
                return RedirectToAction("Index","Home");
            }
            else{
                return View("EditarCasaDeShow");
            }
        }
        public ActionResult DeletarCasaDeShow(int id){
            var casa = _casaDeShowRepositorio.BuscarCasaDeShow(id);
            _casaDeShowRepositorio.DeletarCasaDeShows(casa);
            return RedirectToAction("Index","Home");
        }
    }
}

Controllers/CompraEventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using casaDeShows.Repositorios;
using casaDeShows.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;

namespace casaDeShows.Controllers
{
    public class CompraEventoController : Controller
    {
        private readonly CompraEventoRepositorio _compraEventoRepositorio;
        private readonly EventoRepositorio _eventoRepositorio;
        private readonly GenerosRepositorio _generoRepositorio;
        private readonly CasaDeShowRepositorio _casaDeShowRepositorio;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public CompraEventoController(CompraEventoRepositorio compraEventoRepositorio, EventoRepositorio eventoRepositorio, 
        GenerosRepositorio generoRepositorio, CasaDeShowRepositorio casaDeShowRepositorio, IHttpContextAccessor httpContextAccessor)
        {
            _compraEventoRepositorio = compraEventoRepositorio;
            _eventoRepositorio = eventoRepositorio;
            _generoRepositorio = generoRepositorio;
            _casaDeShowRepositorio = casaDeShowRepositorio;
            _httpContextAccessor = httpContextAccessor;
        }
        [Authorize]
        public IActionResult RealizandoCompra(int id)
        {
            ViewBag.Generos = _generoRepositorio.PegandoListaDeGeneros();
            ViewBag.CasasDeShow = _casaDeShowRepositorio.ListaCasaDeShows();
            var comprarEvento = _eventoRepositorio.BuscarEvento(id);
            var comprar = new CompraEvento()
            {
                Evento = comprarEvento,
                EventoId = id
            };
            return View(comprar);
        }
        [HttpGet]
        public IActionResult IngressosEsgotados(){
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult RealizandoCompra(CompraEvento com)
        {


            CompraEvento comprar = new CompraEvento();
            var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var idEventoComprado = _eventoRepositorio.BuscarEvento(com.Evento.Id);

            if( (idEventoComprado.Capacidade-_compraEventoRepositorio.ContarIngressoVendido(com.Evento.Id) < com.QtdIngresso)){
                return RedirectToAction("IngressosEsgotados");    
            }

            comprar.UserId = userId; //TODO - pegar o id do usuario
            comprar.Evento = idEventoComprado;
            comprar.QtdIngresso = com.QtdIngresso;
            
            _compraEventoRepositorio.FazerCompra(comprar);
            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        [HttpGet]
        public IActionResult Historico()
        {
            var historico = _compraEventoRepositorio.HistoricoDeCompras();
            return View(historico);
        }
    }
}

Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using casaDeShows.Repositorios;
using casaDeShows.Models;
using Microsoft.AspNetCore.Authorization;
namespace casaDeShows.Controllers
{
    public class EventoController:Controller
    {
        private readonly EventoRepositorio _eventoRepositorio;
        private readonly CasaDeShowRepositorio _casaDeShowRepositorio;
        private readonly GenerosRepositorio _generoRepositorio;

        public EventoController(EventoRepositorio eventoRepositorio, CasaDeShowRepositorio casaDeShowRepositorio, GenerosRepositorio generoRepositorio){
            _eventoRepositorio = eventoRepositorio;
            _casaDeShowRepositorio = casaDeShowRepositorio;
            _generoRepositorio = generoRepositorio;
            
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult FaltaEvento(){
            return View();
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult NovoEventoFormulario(){
            ViewBag.Generos = _generoRepositorio.PegandoListaDeGeneros();
            ViewBag.CasasDeShow = _casaDeShowRepositorio.ListaCasaDeShows();
            var checarListaCasaDeshow = _casaDeShowRepositorio.ListaCasaDeShows();
            int tamanhoLista = checarListaCasaDeshow.Count;
            if(tamanhoLista>0){
                return View();
            }
            else{
                return View("FaltaEvento");
            }
        }
        [HttpPost]
        public ActionResult NovoEvento(Evento evento){
            if(ModelState.IsValid){
                _eventoRepositorio.AdicionarEventos(evento);
                 return RedirectToAction("Index","Home");
            }   
            else{
                ViewBag.Generos = _generoRepositorio.PegandoListaDeGeneros();
                ViewBag.CasasDeShow = _casaDeShowRepositorio.ListaCasaDeShows();
                return View("NovoEventoFormulario");
            }
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult EditarEvento(int id){
            ViewBag.Generos = _generoRepositorio.PegandoListaDeGeneros();
            ViewBag.CasasDeShow = _casaDeShowRepositorio.ListaCasaDeShows();
            var editarEvento = _eventoRepositorio.BuscarEvento(id);
            return View(editarEvento);
        }
        [HttpPost]
        public IActionResult EditarEvento(Evento editarEvento){
            if(ModelState.IsValid){
                _eventoRepositorio.EditarEvento(editarEvento);
                return RedirectToAction("Index","Home");
            }
            else{
                return View("EditarEvento");
            }
        }
        public ActionResult DeletarEvento(int id){
            var evento = _eventoRepositorio.BuscarEvento(id);
            _eventoRepositorio.ExcluiEvento(evento);
            return RedirectToAction("Index","Home");
        }

    }
}

Controllers/GeneroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using casaDeShows.Repositorios;
using casaDeShows.Models;
using Microsoft.AspNetCore.Authorization;
namespace casaDeShows.Controllers
{
    public class GeneroController:Controller
    {
        private readonly GenerosRepositorio _generoRepositorio;
        public GeneroController(GenerosRepositorio generosRepositorio){
            _generoRepositorio = generosRepositorio;
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult ListarGeneros(){
            var listaDeGeneros =  _generoRepositorio.MostrarGenerosEventos();
            return View(listaDeGeneros);
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult NovoGeneroFormulario(){
            return View();
        }
        [HttpPost]
        public IActionResult NovoGenero(GeneroEvento novoGenero){
            if(ModelState.IsValid){
                _generoRepositorio.AdicionarGenero(novoGenero);
                return RedirectToAction("Index","Home");
            }
            else{
                return View("NovoGeneroFormulario");
            }   
        }
        public IActionResult DeletarGenero(int id){
            var genero =  _generoRepositorio.BuscarGeneroEvento(id);
            _generoRepositorio.DeletarGenero(genero);
            return RedirectToAction("Index","Home");
        }
        [Authorize(Policy="Admin")]
        [HttpGet]
        public IActionResult EditarGenero(int id){
            var buscarGenero = _generoRepositorio.BuscarGeneroEvento(id);
            return View(buscarGenero);
        }
        [HttpPost]
        public IActionResult EditarGenero(GeneroEvento genero){
            if(ModelState.IsValid){
                _generoRepositorio.Editar(genero);
                return RedirectToAction("Index","Home");
            }
            else{
                return View("EditarGenero");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - casaDeShows</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @using Microsoft.AspNetCore.Identity
    @inject SignInManager<IdentityUser> SignInManager
    @inject UserManager<IdentityUser> UserManager

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>   
                        @if(SignInManager.IsSignedIn(User)){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="CompraEvento" asp-action="Historico">Historico</a>
                            </li>
                            @if(User.Identities.First().Claims.FirstOrDefault(x => x.Type.Equals("NomeUsuario")).Value == "Admin"){
                                <div class="dropdown show">
                                    <a class="nav-link text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Casa de show
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="CasaDeShow" asp-action="ListarCasasDeShow">Ver casas de show</a>
                                        <a class="dropdown-item" asp-controller="Evento" asp-action="NovoEventoFormulario">Novo Evento</a>
                                        <a class="dropdown-item" asp-controller="CasaDeShow" asp-action="NovaCasaDeShowFormulario">Criar casa de show</a>
                                        <a class="dropdown-item" asp-controller="Genero" asp-action="NovoGeneroFormulario">Criar novo genero</a>
                                        <a class="dropdown-item" asp-controller="Genero" asp-action="ListarGeneros">Ver todos os generos</a>
                                    </div>
                                </div>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>